# numpy 专门用来处理数组的库，数据结构只有一种：array

In [2]:
import numpy as np

## 一、创建一个array（最常用的为二维数组，也就是数值矩阵）
### array中最常见的数据类型：'float', 'int', 'bool'

In [3]:
"""
np.array(list) 创建数组

"""
a = np.array([1,2,3]) # 一维数组
b = np.array([[1,2], [3,4]]) # 创建二维数组
a,b

(array([1, 2, 3]),
 array([[1, 2],
        [3, 4]]))

In [4]:
np.array([[1, 2], [3, 4]], dtype='float32') # 可以通过设置dtype参数来指定数据类型

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [5]:
"""
array.astype(str) 可以通过astype改变数据类型
"""
d = np.array([1, '1'], dtype='object')  # object类型相当于所有类型的父类
b = b.astype('float32')  # 可以通过astype改变数据类型

"""
array.tolist() 转化为python中数组
"""
d = d.tolist() 
b, d, type(d)   # type(instance) 查看实例的类型

(array([[1., 2.],
        [3., 4.]], dtype=float32),
 [1, '1'],
 list)

### 其他创建数组的方法

In [6]:
"""
np.arange() 类似于python中的range()方法
"""
np.arange(10), np.arange(1, 8, 2)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7]))

In [8]:
"""
np.linspace() 等距生成数组
endpoint=False 表示终值是否作为生成的元素
"""
np.linspace(1,10,4, endpoint=False), np.linspace(1,10,4, endpoint=True)

(array([1.  , 3.25, 5.5 , 7.75]), array([ 1.,  4.,  7., 10.]))

In [9]:
"""
np.zeros(tuple)  创建指定维度的全0数组
np.ones(tuple)   创建制定维度的全1数组
"""
np.zeros((3,4), dtype='float32'), np.ones((2,3,4), dtype='int8') # 创建一个3x4的全0数组，创建一个2x3x4的全1数组

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32),
 array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=int8))

In [10]:
"""
np.full() 使用指定值来填充数组
"""
np.full((3, 1), 2) # 生成一个3x1的数组，每个元素都为2

array([[2],
       [2],
       [2]])

In [11]:
"""
np.eye() 生成单位矩阵
"""
np.eye(4, 4, dtype='float32')

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [13]:
"""
array.reshape(tuple) 重新组合
"""

a = np.arange(12, dtype='int8').reshape((3, 4))
# np.zeros_like(a)   np.full_like (a, val) np.ones_like(a)
a, np.ones_like(a), np.full_like(a, 3)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=int8),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=int8),
 array([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]], dtype=int8))

In [15]:
"""
array.copy() 拷贝数组，有时候不能改变原数组
"""
a = np.arange(5)
b = a
b[3] = 100
print(a)            # 此时a数组被改变了

c = a.copy()
c[3] = 3      # 使用copy创建的新数组不会影响原数组

print(c)
print(a)

[  0   1   2 100   4]
[0 1 2 3 4]
[  0   1   2 100   4]


## 二、查看数组的一些属性

In [16]:
"""
shape 查看形状
ndim 查看维度
dtype 查看元素的数据类型
type(instance) 查看实例数据类型
size: 查看元素的总个数
"""
a = np.arange(15).reshape((3, 5))
a, a.shape,a.ndim,a.dtype,a.size, type(a)

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 (3, 5),
 2,
 dtype('int32'),
 15,
 numpy.ndarray)

## 三、修改数组中的元素