# numpy 专门用来处理数组的库，数据结构只有一种：array

In [1]:
import numpy as np

## 一、创建一个array（最常用的为二维数组，也就是数值矩阵）
### array中最常见的数据类型：'float', 'int', 'bool'

In [3]:
"""
np.array(list) 创建数组

"""
a = np.array([1,2,3]) # 一维数组
b = np.array([[1,2], [3,4]]) # 创建二维数组
a,b

(array([1, 2, 3]),
 array([[1, 2],
        [3, 4]]))

In [4]:
np.array([[1, 2], [3, 4]], dtype='float32') # 可以通过设置dtype参数来指定数据类型

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [5]:
"""
array.astype(str) 可以通过astype改变数据类型
"""
d = np.array([1, '1'], dtype='object')  # object类型相当于所有类型的父类
b = b.astype('float32')  # 可以通过astype改变数据类型

"""
array.tolist() 转化为python中数组
"""
d = d.tolist() 
b, d, type(d)   # type(instance) 查看实例的类型

(array([[1., 2.],
        [3., 4.]], dtype=float32),
 [1, '1'],
 list)

### 其他创建数组的方法

In [6]:
"""
np.arange() 类似于python中的range()方法
"""
np.arange(10), np.arange(1, 8, 2)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7]))

In [8]:
"""
np.linspace() 等距生成数组
endpoint=False 表示终值是否作为生成的元素
"""
np.linspace(1,10,4, endpoint=False), np.linspace(1,10,4, endpoint=True)

(array([1.  , 3.25, 5.5 , 7.75]), array([ 1.,  4.,  7., 10.]))

In [9]:
"""
np.zeros(tuple)  创建指定维度的全0数组
np.ones(tuple)   创建制定维度的全1数组
"""
np.zeros((3,4), dtype='float32'), np.ones((2,3,4), dtype='int8') # 创建一个3x4的全0数组，创建一个2x3x4的全1数组

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32),
 array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=int8))

In [10]:
"""
np.full() 使用指定值来填充数组
"""
np.full((3, 1), 2) # 生成一个3x1的数组，每个元素都为2

array([[2],
       [2],
       [2]])

In [11]:
"""
np.eye() 生成单位矩阵
"""
np.eye(4, 4, dtype='float32')

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [13]:
"""
array.reshape(tuple) 重新组合
"""

a = np.arange(12, dtype='int8').reshape((3, 4))
# np.zeros_like(a)   np.full_like (a, val) np.ones_like(a)
a, np.ones_like(a), np.full_like(a, 3)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=int8),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=int8),
 array([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]], dtype=int8))

In [15]:
"""
array.copy() 拷贝数组，有时候不能改变原数组
"""
a = np.arange(5)
b = a
b[3] = 100
print(a)            # 此时a数组被改变了

c = a.copy()
c[3] = 3      # 使用copy创建的新数组不会影响原数组

print(c)
print(a)

[  0   1   2 100   4]
[0 1 2 3 4]
[  0   1   2 100   4]


## 二、查看数组的一些属性

In [16]:
"""
shape 查看形状
ndim 查看维度
dtype 查看元素的数据类型
type(instance) 查看实例数据类型
size: 查看元素的总个数
"""
a = np.arange(15).reshape((3, 5))
a, a.shape,a.ndim,a.dtype,a.size, type(a)

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 (3, 5),
 2,
 dtype('int32'),
 15,
 numpy.ndarray)

## 三、修改数组中的元素

In [2]:
"""
append 在尾部添加元素
"""
a = np.arange(10)
a, np.append(a, 10), np.append(a, [31,32])

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 31, 32]))

In [3]:
"""
insert 指定位置插入
"""
np.insert(a, 1, 100)

array([  0, 100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [4]:
"""
根据索引直接修改
"""
a[0] = -1
a

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [5]:
a = np.array([[1,2,3],[11,22,33],[111,222,333]])
a[0, 2] = 9
a

array([[  1,   2,   9],
       [ 11,  22,  33],
       [111, 222, 333]])

In [7]:
"""
concatenate((array1,array2...), axis) 根据坐标轴合并两个数组
"""
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

## 四、从数组中提取特定值（切片操作）
### 与python的切片操作类似

In [11]:
a = np.arange(15).reshape((3, 5))
a, a[0], a[:, 0], a[2, 3], a[0, 2:4], a[::2] # 第一行，第一列，第3行第4列的元素，第一行第3第4元素组成的数组，步长为2取值

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([0, 1, 2, 3, 4]),
 array([ 0,  5, 10]),
 13,
 array([2, 3]),
 array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]))

In [12]:
"""
使用切片手写一个补零操作
"""
def zero_pad(in_array, padding_size=0):
    rows, cols = in_array.shape
    pad_array = np.zeros((rows + 2 * padding_size, cols + 2 * padding_size))
    pad_array[padding_size:rows + padding_size, padding_size:cols + padding_size] = in_array  # 使用切片
    return pad_array

x = np.array([[1, 2, 3, 4, 5],
                [4, 5, 6, 7, 8],
                [9, 8, 7, 6, 5],
                [1, 2, 3, 4, 5],
                [2, 3, 4, 5, 6],
                [2, 3, 4, 5, 6],
                [2, 3, 4, 5, 6]])
y = zero_pad(x, 2)
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 2., 3., 4., 5., 0., 0.],
       [0., 0., 4., 5., 6., 7., 8., 0., 0.],
       [0., 0., 9., 8., 7., 6., 5., 0., 0.],
       [0., 0., 1., 2., 3., 4., 5., 0., 0.],
       [0., 0., 2., 3., 4., 5., 6., 0., 0.],
       [0., 0., 2., 3., 4., 5., 6., 0., 0.],
       [0., 0., 2., 3., 4., 5., 6., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
a[::-1, ]  # 将行翻转

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [14]:
a[ : ,::-1] # 将列翻转

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10]])

In [15]:
a[::-1, ::-1] # 全翻转

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [18]:
np.flip(a, axis=0), np.flip(a, axis=1)

(array([[10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4]]),
 array([[ 4,  3,  2,  1,  0],
        [ 9,  8,  7,  6,  5],
        [14, 13, 12, 11, 10]]))