In [1]:
import numpy as np

# axis 轴
## 对于一维数组而言，就只有一个轴  axis=0
## 对于二维数组，存在两个轴 axis=0，axis=1 分别对应行和列的维度
## 多维数组（常见为三维和四维） 三维数组CHW，axis=0，1,2表示c，h，w 同理四维数组BCHW axis=0，1，2，3

In [2]:
a = np.arange(18).reshape((3, 3, 2))
a, a[0,:,:], a[:,0,:], a[:,:,0]

(array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]],
 
        [[12, 13],
         [14, 15],
         [16, 17]]]),
 array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]))

## 数值计算

In [3]:
# 除了正常的数值，np还有着缺失值和无限大两个值。其数据类型为float

a = np.array([[1, 2], [3, 4]], dtype='float32')   
a[0, 0] = np.nan   # 缺失值
a[1, 1] = np.inf   # 无限大
a, type(np.nan)         # 由于np.nan和inf数据类型为float，数组类型也必须为float

(array([[nan,  2.],
        [ 3., inf]], dtype=float32),
 float)

In [4]:
a = np.array( [20,30,40,50] )
b = np.arange(1, 5)
a+b,a-b,a*b,a/b

(array([21, 32, 43, 54]),
 array([19, 28, 37, 46]),
 array([ 20,  60, 120, 200]),
 array([20.        , 15.        , 13.33333333, 12.5       ]))

In [5]:
"""
矩阵运算
"""
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )
A * B, A.T, np.dot(A, B) # 元素相乘，转置，矩阵相乘

(array([[2, 0],
        [0, 4]]),
 array([[1, 0],
        [1, 1]]),
 array([[5, 4],
        [3, 4]]))

## 统计函数

In [6]:
a = np.array([[20, 1, 8, 3, 5],
            [6, 16, 37, 2, 9],
            [4, 7, 12, 30, 0]])
a, a.max(), a.min(), a.sum()   # 最大值，最小值，求和

(array([[20,  1,  8,  3,  5],
        [ 6, 16, 37,  2,  9],
        [ 4,  7, 12, 30,  0]]),
 37,
 0,
 160)

In [7]:
# 指定轴比较大小，axis=0表示行与行之间比较大小
a.max(axis=0), a.min(axis=0), a.sum(axis=0)

(array([20, 16, 37, 30,  9]),
 array([4, 1, 8, 2, 0]),
 array([30, 24, 57, 35, 14]))

In [8]:
a.max(axis=1), a.min(axis=1), a.sum(axis=1)

(array([20, 37, 30]), array([1, 2, 0]), array([37, 70, 53]))

In [9]:
a.mean(), a.std(), a.var()  # 均值， 标准差， 方差

(10.666666666666666, 10.479609831583533, 109.82222222222224)

In [10]:
a.mean(axis=0), a.std(axis=0), a.var(axis=0),a.mean(axis=1), a.std(axis=1), a.var(axis=1)

(array([10.        ,  8.        , 19.        , 11.66666667,  4.66666667]),
 array([ 7.11805217,  6.164414  , 12.83225104, 12.97005097,  3.68178701]),
 array([ 50.66666667,  38.        , 164.66666667, 168.22222222,
         13.55555556]),
 array([ 7.4, 14. , 10.6]),
 array([ 6.71118469, 12.37739876, 10.46135746]),
 array([ 45.04, 153.2 , 109.44]))

In [11]:
a.argmax(), a.argmin()  # 最大值的索引,最小值的索引

(7, 14)

In [12]:
a.argmax(axis=0), a.argmin(axis=0), a.argmax(axis=1), a.argmin(axis=1)

(array([0, 1, 1, 2, 1], dtype=int64),
 array([2, 0, 0, 1, 2], dtype=int64),
 array([0, 2, 3], dtype=int64),
 array([1, 3, 4], dtype=int64))

## 常用的计算函数

In [13]:
# np.power(a, 2)  # 幂次函数
# np.abs() 求绝对值
# np.log() ln函数
# np.exp() 指数函数
# np.sqrt() 开方函数
# np.maximum(x1, x2) 逐元素对比两个数组，选出较大值
# np.minimum(x1, x2) 逐元素对比两个数组，选出较小值
# np.ceil() # 向上取整
# np.floor() # 向下取整

## 数组形状操作

In [23]:
a = np.arange(12).reshape(3, 4)
a, a.reshape(4, 3)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [24]:
"""
reshape和resize是有区别的，reshape不会改变原数组会输出改变后的数组，resize会直接改变原数组无输出值
"""
a.resize(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
"""
展平操作：flatten和ravel：由ravel创建的数组会影响原数组，而flatten不会
"""
a = np.arange(12).reshape(3, 4)
b = a.flatten()
c = a.ravel()
a,b,c

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [26]:
b[3] = 100
a, b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11]))

In [27]:
c[3] = 100   # 可以看到a也随之发生改变
a, c

(array([[  0,   1,   2, 100],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]]),
 array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11]))

## 数组堆叠

In [28]:
a = np.array([[9., 7.],
              [5., 2.]])
b = np.array([[1., 9.],
              [5., 1.]])
c = np.vstack((a, b))   # 将行进行堆叠
d = np.hstack((a, b))   # 将列进行堆叠
c, d

(array([[9., 7.],
        [5., 2.],
        [1., 9.],
        [5., 1.]]),
 array([[9., 7., 1., 9.],
        [5., 2., 5., 1.]]))

In [34]:
"""
stack是在维度上添加新的维度，和vstack hstack不一致
"""
e = np.stack((a, b), axis=0)
f = np.stack((a, b), axis=1) 
e, e.shape, f, f.shape

(array([[[9., 7.],
         [5., 2.]],
 
        [[1., 9.],
         [5., 1.]]]),
 (2, 2, 2),
 array([[[9., 7.],
         [1., 9.]],
 
        [[5., 2.],
         [5., 1.]]]),
 (2, 2, 2))

In [35]:
# concat和hstack vstack一致
np.concatenate((a, b), axis=0), np.concatenate((a, b), axis=1)

(array([[9., 7.],
        [5., 2.],
        [1., 9.],
        [5., 1.]]),
 array([[9., 7., 1., 9.],
        [5., 2., 5., 1.]]))

## 数组切分

In [36]:
a = np.array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
              [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])

In [37]:
np.hsplit(a,2)      # 将a对列切2份      

[array([[6., 7., 6., 9., 0., 5.],
        [8., 5., 5., 7., 1., 8.]]),
 array([[4., 0., 6., 8., 5., 2.],
        [6., 7., 1., 8., 1., 0.]])]

In [38]:
np.vsplit(a,2)      # 将a对行切2份

[array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.]]),
 array([[8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])]

In [39]:
np.split(a,2)      # 将a对行切2份

[array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.]]),
 array([[8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])]

In [40]:
np.split(a, 3, axis=1)      # 将a对列切3份

[array([[6., 7., 6., 9.],
        [8., 5., 5., 7.]]),
 array([[0., 5., 4., 0.],
        [1., 8., 6., 7.]]),
 array([[6., 8., 5., 2.],
        [1., 8., 1., 0.]])]

In [41]:
# 实现不均匀切分
a = np.hsplit(a, (3, 4))      # 在列索引为3处切，在列索引为4处切
a ,a[1]

([array([[6., 7., 6.],
         [8., 5., 5.]]),
  array([[9.],
         [7.]]),
  array([[0., 5., 4., 0., 6., 8., 5., 2.],
         [1., 8., 6., 7., 1., 8., 1., 0.]])],
 array([[9.],
        [7.]]))