In [1]:
import numpy as np

## 随机数

In [2]:
# np.random.rand(d0,d1,...,dn) 可以返回一组n维度服从“0~1”均匀分布的随机样本值。随机样本取值范围是[0,1)
np.random.rand(5)

array([0.5059709 , 0.8607669 , 0.04462443, 0.31231238, 0.02112278])

In [3]:
np.random.rand(2,3) # 生成二维数组

array([[0.33167551, 0.19694525, 0.58532772],
       [0.21285314, 0.52978678, 0.454472  ]])

In [4]:
np.random.rand()    # 生成一个标量

0.8340442642185474

In [5]:
# np.random.normal(loc=0,scale=1e-2,size=shape) 可以返回一组n维度服从正态分布的随机样本值。
# 参数loc(float)：正态分布的均值，对应着这个分布的中心。loc=0说明这一个以Y轴为对称轴的正态分布
# 参数scale(float)：正态分布的标准差，对应分布的宽度，scale越大，正态分布的曲线越矮胖，scale越小，曲线越高瘦。
# 参数size(int 或者整数元组)：输出的值赋在shape里，默认为None
np.random.normal(0, 0.1, 10)

array([ 0.02876714, -0.05377959,  0.16726859,  0.03392598, -0.12767502,
       -0.04405402, -0.00569426, -0.02874137,  0.03966182, -0.04322861])

In [6]:
# np.random.randn(d0,d1,...,dn) 可以返回一组n维度服从标准正态分布的随机样本值。
np.random.randn(2,5)

array([[ 1.07796264,  1.12959007,  1.15214713,  0.36388902,  0.33727802],
       [-0.93541029, -0.21593689, -0.74910998, -0.69016528,  0.38682745]])

In [11]:
# np.random.randint(low,high,size,)返回low<= n <high范围的整数
np.random.randint(0, 4, size=10)  # 单值则为最大值

array([2, 1, 2, 2, 1, 0, 3, 1, 3, 3])

In [12]:
np.random.randint(2, size=(2,3)) # size可以生成指定形状数组

array([[0, 1, 0],
       [0, 0, 1]])